In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
profit = pd.read_csv('/content/50_Startups.csv')

In [3]:
print(profit.head())

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94


In [4]:
print(profit.tail())

    R&D Spend  Administration  Marketing Spend       State    Profit
45    1000.23       124153.04          1903.93    New York  64926.08
46    1315.46       115816.21        297114.46     Florida  49490.75
47       0.00       135426.92             0.00  California  42559.73
48     542.05        51743.15             0.00    New York  35673.41
49       0.00       116983.80         45173.06  California  14681.40


In [7]:
print(profit.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB
None


In [8]:
print(profit.describe())

           R&D Spend  Administration  Marketing Spend         Profit
count      50.000000       50.000000        50.000000      50.000000
mean    73721.615600   121344.639600    211025.097800  112012.639200
std     45902.256482    28017.802755    122290.310726   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103730.875000    129300.132500   90138.902500
50%     73051.080000   122699.795000    212716.240000  107978.190000
75%    101602.800000   144842.180000    299469.085000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000


In [9]:
X = profit.iloc[:, :-1].values
y = profit.iloc[:, -1].values

In [10]:
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [11]:
X

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [13]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
LabelEncoder = LabelEncoder()
X[:, 3] = LabelEncoder.fit_transform(X[:, 3])
OneHotEncoder = OneHotEncoder(categorical_features = [3])
X = OneHotEncoder.fit_transform(X).toarray()

In [14]:
X

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58

In [15]:
X = X[:, 1:]

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [17]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [18]:
y_pred = regressor.predict(X_test)
print(y_pred)

[103015.20159796 132582.27760816 132447.73845175  71976.09851259
 178537.48221054 116161.24230163  67851.69209676  98791.73374688
 113969.43533012 167921.0656955 ]


In [19]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [20]:
pd = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})

In [21]:
print(pd)

   Real Values  Predicted Values
0    103282.38     103015.201598
1    144259.40     132582.277608
2    146121.95     132447.738452
3     77798.83      71976.098513
4    191050.39     178537.482211
5    105008.31     116161.242302
6     81229.06      67851.692097
7     97483.56      98791.733747
8    110352.25     113969.435330
9    166187.94     167921.065696


In [23]:
import statsmodels.api as sm
X = np.append(arr = np.ones((50, 1)).astype(int), values = X, axis = 1)
print(X)

[[1 1 0.0 1.0 165349.2 136897.8 471784.1]
 [1 1 0.0 0.0 162597.7 151377.59 443898.53]
 [1 1 1.0 0.0 153441.51 101145.55 407934.54]
 [1 1 0.0 1.0 144372.41 118671.85 383199.62]
 [1 1 1.0 0.0 142107.34 91391.77 366168.42]
 [1 1 0.0 1.0 131876.9 99814.71 362861.36]
 [1 1 0.0 0.0 134615.46 147198.87 127716.82]
 [1 1 1.0 0.0 130298.13 145530.06 323876.68]
 [1 1 0.0 1.0 120542.52 148718.95 311613.29]
 [1 1 0.0 0.0 123334.88 108679.17 304981.62]
 [1 1 1.0 0.0 101913.08 110594.11 229160.95]
 [1 1 0.0 0.0 100671.96 91790.61 249744.55]
 [1 1 1.0 0.0 93863.75 127320.38 249839.44]
 [1 1 0.0 0.0 91992.39 135495.07 252664.93]
 [1 1 1.0 0.0 119943.24 156547.42 256512.92]
 [1 1 0.0 1.0 114523.61 122616.84 261776.23]
 [1 1 0.0 0.0 78013.11 121597.55 264346.06]
 [1 1 0.0 1.0 94657.16 145077.58 282574.31]
 [1 1 1.0 0.0 91749.16 114175.79 294919.57]
 [1 1 0.0 1.0 86419.7 153514.11 0.0]
 [1 1 0.0 0.0 76253.86 113867.3 298664.47]
 [1 1 0.0 1.0 78389.47 153773.43 299737.29]
 [1 1 1.0 0.0 73994.56 122782.75 3

In [28]:
import statsmodels.api as sm

# Add a column of ones for the intercept term
X = np.append(arr = np.ones((50, 1)).astype(int), values = X, axis = 1)

# Select the columns for the OLS model, ensuring they are numeric
# The first column is the intercept, followed by the one-hot encoded state columns
# and then the original numerical features.
X_opt = X[:, [0, 1, 2, 3, 4, 5]].astype(float)

regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
print(regressor_OLS.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.024
Model:                            OLS   Adj. R-squared:                 -0.018
Method:                 Least Squares   F-statistic:                    0.5748
Date:                Tue, 24 Jun 2025   Prob (F-statistic):              0.567
Time:                        19:17:37   Log-Likelihood:                -600.05
No. Observations:                  50   AIC:                             1206.
Df Residuals:                      47   BIC:                             1212.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.598e+04   2465.409     10.536      0.0

In [29]:
X_opt = X[:, [0, 3, 5]].astype(float)
regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
print(regressor_OLS.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                 -0.020
Method:                 Least Squares   F-statistic:                   0.04727
Date:                Tue, 24 Jun 2025   Prob (F-statistic):              0.829
Time:                        19:17:41   Log-Likelihood:                -600.63
No. Observations:                  50   AIC:                             1205.
Df Residuals:                      48   BIC:                             1209.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.556e+04   3542.814     15.682      0.0